name: Build

on:
  push:
    branches:
      - main
      - stable
      - release
    tags:
      - v*

jobs:
  publish-drn:
    uses: ./.github/workflows/publish.yaml
    with:
      context: .
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-drn
      branch: ${{ github.ref_name }}
      base_image: bikenow.vkw.tu-dresden.de/priobike/priobike-graphhopper-drn:${{ github.ref_name }}
      osm_file_path: /graphhopper/map.osm
      overpass_planet_preprocess: 'mv /db/planet.osm.bz2 /db/planet.osm && osmium cat -o /db/planet.osm.bz2 /db/planet.osm && rm /db/planet.osm'
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

  publish-osm-hamburg:
    uses: ./.github/workflows/publish.yaml
    with:
      context: .
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-osm-hamburg
      branch: ${{ github.ref_name }}
      base_image: bikenow.vkw.tu-dresden.de/priobike/priobike-graphhopper-hamburg:${{ github.ref_name }}
      osm_file_path: /graphhopper/hamburg-latest.osm.pbf
      overpass_planet_preprocess: 'mv /db/planet.osm.bz2 /db/planet.osm.pbf && osmium cat -o /db/planet.osm.bz2 /db/planet.osm.pbf && rm /db/planet.osm'
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

  publish-osm-sachsen:
    uses: ./.github/workflows/publish.yaml
    with:
      context: .
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-osm-sachsen
      branch: ${{ github.ref_name }}
      base_image: bikenow.vkw.tu-dresden.de/priobike/priobike-graphhopper-sachsen:${{ github.ref_name }}
      osm_file_path: /graphhopper/sachsen-latest.osm.pbf
      overpass_planet_preprocess: 'mv /db/planet.osm.bz2 /db/planet.osm.pbf && osmium cat -o /db/planet.osm.bz2 /db/planet.osm.pbf && rm /db/planet.osm'
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}