name: Create and publish Docker image

on:
  workflow_call:
    inputs:
      context:
        description: 'The Docker build context'
        required: true
        type: string
      registry:
        description: 'The Docker registry'
        required: true
        type: string
      image:
        description: 'The Docker image name'
        required: true
        type: string
      branch:
        description: 'The branch to build'
        required: true
        type: string
      base_image:
        description: 'The base image to use (where the OSM file is stored)'
        required: true
        type: string
      osm_file_path:
        description: 'The path to the OSM file in the base image'
        required: true
        type: string
      overpass_planet_preprocess:
        description: 'The command to preprocess the OSM file from the base image (for overpass it has to be in .bz2 format)'
        required: true
        type: string
    secrets:
      NEXUS_DOCKER_PUB_USERNAME:
        description: 'Username for the Nexus Docker registry'
        required: true
      NEXUS_DOCKER_PUB_PASSWORD:
        description: 'Password for the Nexus Docker registry'
        required: true

jobs:
  publish:
    runs-on: self-hosted
    container: docker:latest
  
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
          password: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # See: https://github.com/docker/metadata-action
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.registry }}/${{ inputs.image }}
          tags: |
            type=raw,value=${{ inputs.branch }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          push: true
          target: runner
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CACHE_DATE=${{ github.event.repository.updated_at }}-${{ github.run_id }}-${{ github.run_attempt }}
            BASE_IMAGE=${{ inputs.base_image }}
            OSM_FILE_PATH=${{ inputs.osm_file_path }}
            OVERPASS_PLANET_PREPROCESS=${{ inputs.overpass_planet_preprocess }}